_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.8
            "5": 0.19.6
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
        viz:
            confusion_matrix:
                historyFieldSettings:
                    key: confusion_matrix
                    x-axis: _step
                id: wandb/confusion_matrix/v1
